const replacements = {
	"Radicado_expediente": "20-182506",
	"Queja_o_denuncia": "20-182506-0",
	"Fecha_de_la_queja": "18 de junio de 2020",
	"Investigada": "IBEROMODA S.A.S.",
	"No_Id_NIT_O_CC": "900.207.065-3",
	"Radicado_requerimiento": "20-182506-2",
	"Fecha_del_requerimiento": "10 de septiembre de 2020",
	"Fecha_plazo_para_entregar_documentos": "15 días hábiles",
	"Fecha_de_entrega_del_oficio_de_reque": "N/A",
	"Dirección_investigada": "Bg Guadalete Vrd Fusca Aut Norte Km 21",
	"Ciudad_de_la_investigada": "Chía, Cundinamarca",
	"Certificado_de_trazabilidad": "Certificación radicada Nº 20-182506-22",
	"No_De_consecutivo": "20-182506-6",
	"Resolución_de_la_investigación_Administr": "48704",
	"Fecha_de_la_resolución_de_invest": "27 de julio de 2022",
	"Resolución_de_la_sanción": "5930",
	"Fecha_de_la_resolución_de_sanción": "28 de febrero de 2024",
	"Valor_de_la_multa": "N/A",
	"Número_de_salarios_m_": "N/A",
	"Número_UVB": "N/A",
	"Fecha_de_notificación_de_la_sanción": "N/A",
	"Radicado_de_certificado_de_notificación": "20-182506-27",
	"Fecha_de_presentación_recurso_de_reposic": "19 de agosto de 2022",
	"Radicado_del_recurso": "20-182506-18",
	"Nombre_del_representante_legal": "MARÍA DEL ROSARIO GÓMEZ JARAMILLO",
	"Cédula_de_ciudadanía_1": "39.695.557",
	"Nombre_del_apoderado": "N/A",
	"Dirección_de_notificación_judicial": "Carrera 7 No. 74 – 21 piso 6",
	"Ciudad_": "Bogotá D.C.",
	"Email_notifficación": "notificaciones@texmoda.com.co",
	"Email_notifficación1": "mrgomez@col-law.com, pvalderrama@col-law.com"
}

module.exports = { replacements };